export const Images = {
    logo: require("../assets/images/logo.png"),
    photo: require("../assets/images/icon_PHOTO_dark.png"),
    camera: require("../assets/images/icon_CAMERA_dark.png"),
    alarm: require("../assets/images/icon_ALARM_dark.png"),
    icon_1_off: require("../assets/images/icon_1_off.png"),
    icon_2_off: require("../assets/images/icon_2_off.png"),
    icon_3_off: require("../assets/images/icon_3_off.png"),
    icon_4_off: require("../assets/images/icon_4_off.png"),
    icon_5_off: require("../assets/images/icon_5_off.png"),
    applogo : require("../assets/images/applogo.png"),
    icon_l_apple: require("../assets/images/icon_l_apple.png"),
    icon_l_google: require("../assets/images/icon_l_google.png"),
    icon_l_naver: require("../assets/images/icon_l_naver.png"),
    icon_l_kakao: require("../assets/images/icon_l_kakao.png"),
    icon_back:require("../assets/images/icon_back.png"),
    icon_check_on:require("../assets/images/icon_check_on.png"),
    icon_check_off:require("../assets/images/icon_check_off.png"),
    icon_rarrow1:require("../assets/images/icon_rarrow1.png"),
    jicon1:require("../assets/images/jicon1.png"),
    jicon2:require("../assets/images/jicon2.png"),
    jicon3:require("../assets/images/jicon3.png"),
    jicon4:require("../assets/images/jicon4.png"),
    main1:require("../assets/images/main1.png"),
    main2:require("../assets/images/main2.png"),
    main3:require("../assets/images/main3.png"),
    icon_search:require("../assets/images/icon_search.png"),
    icon_cart:require("../assets/images/icon_cart.png"),
    icon_more:require("../assets/images/icon_more.png"),
    testimg:require("../assets/images/testimg.png"),
    icon_alarm:require("../assets/images/icon_alarm.png"),
    icon_arrow_right:require("../assets/images/icon_arrow_right.png"),
    tmpbanner:require("../assets/images/tmpbanner.png"),
    icon_my1:require("../assets/images/icon_my1.png"),
    icon_my2:require("../assets/images/icon_my2.png"),
    icon_my3:require("../assets/images/icon_my3.png"),
    icon_my4:require("../assets/images/icon_my4.png"),
    icon_my5:require("../assets/images/icon_my5.png"),
    icon_close_white:require("../assets/images/icon_close_white.png"),
    qr:require("../assets/images/qr.png"),
    icon_s1:require("../assets/images/icon_s1.png"),
    icon_s2:require("../assets/images/icon_s2.png"),
    grade:require("../assets/images/grade.png"),
    icon_q:require("../assets/images/icon_q.png"),
    icon_config:require("../assets/images/icon_config.png"),
    grade1:require("../assets/images/grade1.png"),
    icon_close:require("../assets/images/icon_close.png"),
    icon_down:require("../assets/images/icon_down.png"),
    icon_share:require("../assets/images/icon_share.png"),
    icon_heart:require("../assets/images/icon_heart.png"),
    icon_minus:require("../assets/images/icon_minus.png"),
    icon_plus:require("../assets/images/icon_plus.png"),
    icon_chs_on:require("../assets/images/icon_chs_on.png"),
    icon_chs_off:require("../assets/images/icon_chs_off.png"),
    icon_ch_off:require("../assets/images/icon_ch_off.png"),
    icon_ch_on:require("../assets/images/icon_ch_on.png"),
    icon_close_dark:require("../assets/images/icon_close_dark.png"),
    icon_scan:require("../assets/images/icon_scan.png"),
    icon_heartg_off:require("../assets/images/icon_heartg_off.png"),
    icon_heartg_on:require("../assets/images/icon_heartg_on.png"),
    icon_info:require("../assets/images/icon_info.png"),
    icon_radio_off:require("../assets/images/icon_radio_off.png"),
    icon_radio_on:require("../assets/images/icon_radio_on.png"),
    icon_help:require("../assets/images/icon_help.png"),
    icon_gift:require("../assets/images/icon_gift.png"),

};
